name: Nuget Package
on:
  #   push:
  #     branches:
  #       - master
  #   pull_request:
  #     types: [closed]
  #     branches:
  #       - master
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .Net
        uses: actions/setup-dotnet@v1

      - name: Build & Packing
        env:
          releaseVersion: ${{ github.event.release.tag_name }}
        run: |
          echo "pack version $releaseVersion"
          dotnet restore
          dotnet build -c Release 
          dotnet pack /p:Version="$releaseVersion" /p:RepositoryUrl="https://github.com/csharp-extensions/General" -c Release -o deploy

      - name: Publish Nuget Package
        run: |
          ls -l deploy
          dotnet nuget push ./deploy/*.nupkg --skip-duplicate --no-symbols true --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
